sudo: false

os:
- osx

before_script: brew update
script: brew audit Formula/dbxcli.rb --online

git:
  depth: 1

branches:
  only:
  - master

before_cache:
  - brew cleanup

cache:
  bundler: true
  directories:
    - $HOME/Library/Caches/Homebrew

notifications:
  email: false
